name: Node Js Setup

on:
  workflow_dispatch
jobs:
  node-js:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '22'
      - name: Print Node Version
        run : node -v


  
  
