name: Reusable workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v4.2.2
       - name: Run Resuable Build Step
         run: echo "This is a resuable workflow"
